games/urls.py
from django.urls import path

from .views import ListGamesView

app_name = 'games'
urlpatterns = [
    path('', ListGamesView.as_view(), name='list'),
]

users/urls.py
from django.urls import path

from .views import RegisterView, LoginView, PasswordChangeView, activate_account
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('change-password/', PasswordChangeView.as_view(), name='change-password'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page = reverse_lazy('users:login')), name='logout'),
    path('activate/<uidb64>/<token>/', activate_account, name='activate'),
]

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import math

from django.contrib.auth.models import AbstractUser
from django.db import models

from pinax.points.models import points_awarded
from pinax.points.signals import points_awarded as points_awarded_signal

class User(AbstractUser):
    display_name = models.CharField(max_length=64)
    level = models.IntegerField(default = 1)
    public_profile = models.BooleanField(default=True)

    def __str__(self):
        return self.display_name or self.username


    @property
    def experience(self):
        return points_awarded(self)

    @property
    def next_level_threshold(self):
        return User.compute_level_treshold(self.level+1)

    @property
    def next_level_progress(self):
        base_treshold = User.compute_level_treshold(self.level)
        exp = self.experience - base_treshold
        required = self.next_level_threshold - base_treshold
        return int(exp / required * 100)

    @property
    def latest_awards(self):
        return self.awardedpointvalue_targets.all()[:5]


    def update_level(self):
        expected_level = int((1 + math.sqrt(1 + 8 * self.experience / 50)) / 2)

        while self.level < expected_level:
            self.level += 1
            # send notification

        self.save()

    @staticmethod
    def compute_level_treshold(level):
        return ((level ** 2 - level) * 50 ) // 2


def user_level_up(target, key, points, source, **kwargs):

    print(target, key, points, source)
    if isinstance(target, User):
        target.update_level()

points_awarded_signal.connect(user_level_up)

users/forms.py
from django import forms
import django.contrib.auth.forms as auth_forms # UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.conf import settings
from django.template.loader import render_to_string
from django.core.mail import send_mail
from .models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field, Submit, Button, Div
from crispy_forms.bootstrap import FormActions

class PasswordChangeForm(auth_forms.PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


class LoginForm(auth_forms.AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

class RegisterForm(auth_forms.UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )


    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False


    def save(self, request):

        # Save user as inactive (activation mail will be send)
        user = super(RegisterForm, self).save(commit=False)
        user.is_active = False
        user.save()

        context = {
            # 'from_email': settings.DEFAULT_FROM_EMAIL,
            'request': request,
            'protocol': request.scheme,
            'username': self.cleaned_data.get('username'),
            'domain': request.META['HTTP_HOST'],
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': default_token_generator.make_token(user),
        }

        subject = "Action Required to Complete the Account Creation"
        email = render_to_string('users/email/activation_email.html', context)

        send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, [user.email])

        return user

users/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.contrib.auth import views as auth_views

from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from .forms import RegisterForm, LoginForm, PasswordChangeForm
from .models import User

# Create your views here.

class PasswordChangeView(auth_views.PasswordChangeView):
    form_class = PasswordChangeForm
    template_name='users/password_change.html'
    success_url = reverse_lazy("home")

class LoginView(auth_views.LoginView):

    form_class = LoginForm
    success_url = reverse_lazy("home")
    template_name = "users/login.html"


class RegisterView(FormView):

    template_name = "users/registration.html"
    form_class = RegisterForm

    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        form.save(self.request)

        return super().form_valid(form)


def activate_account(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()
        # messages.add_message(request, messages.INFO, 'Account activated. Please login.')
    else:
        # messages.add_message(request, messages.INFO, 'Link Expired. Contact admin to activate your account.')
        pass

    return redirect("users:login")

users/templates/users/login.html
{% load crispy_forms_tags %}
{% load static %} 
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="author" content="ThemePixels">

    <title>Bracket Plus Responsive Bootstrap 4 Admin Template</title>

    <!-- vendor css -->
    <link href="{% static "lib/@fortawesome/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/ionicons/css/ionicons.min.css" %}" rel="stylesheet">

    <!-- Bracket CSS -->
    <link rel="stylesheet" href="{% static "css/bracket.css" %}">
  </head>

  <body>

    <div class="d-flex align-items-center justify-content-center bg-br-primary ht-100v">

      <div class="login-wrapper wd-300 wd-xs-350 pd-25 pd-xs-40 bg-white rounded shadow-base">
        <div class="signin-logo tx-center tx-28 tx-bold tx-inverse"><span class="tx-normal">[</span> bracket <span class="tx-info">plus</span> <span class="tx-normal">]</span></div>
        <div class="tx-center mg-b-60">The Admin Template For Perfectionist</div>

        <form method="post">
          {% csrf_token %}
          {% crispy form %}
          <button type="submit" class="btn btn-info btn-block">{% trans "Sign In" %}</button>

          <div class="mg-t-60 tx-center">{% trans "Not yet a member?" %} <a href="{% url 'users:register' %}" class="tx-info">{% trans "Sign Up" %}</a></div>
        </form>
      </div><!-- login-wrapper -->
    </div><!-- d-flex -->

    <script src="{% static "lib/jquery/jquery.min.js" %}"></script>
    <script src="{% static "lib/jquery-ui/ui/widgets/datepicker.js" %}"></script>
    <script src="{% static "lib/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

  </body>
</html>

users/templates/users/password_change.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}


  <div class="row mg-t-80">
    <div class="col-xl-6 offset-xl-3">
      <form method="POST">
      <div class="form-layout form-layout-4">
        <h6 class="br-section-label mg-t-0">{% trans "Change password" %}</h6>
        <p class="br-section-text">{% trans "Setup new password for your account" %} </p>
        {% crispy form %}
        <button type='submit' class='btn btn-primary'> {% trans "Change password" %} </button>
      </div><!-- form-layout -->
      </form>
    </div><!-- col-6 -->
  </div>

{% endblock %}

users/templates/users/registration.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Meta -->
    <meta name="description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="author" content="ThemePixels">

    <title>Bracket Plus Responsive Bootstrap 4 Admin Template</title>

    <!-- vendor css -->
    <link href="{% static "lib/@fortawesome/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/ionicons/css/ionicons.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/select2/css/select2.min.css" %}" rel="stylesheet">

    <!-- Bracket CSS -->
    <link rel="stylesheet" href="{% static "css/bracket.css" %}">
  </head>

  <body>

    <div class="d-flex align-items-center justify-content-center bg-br-primary ht-100v">

      <div class="login-wrapper wd-300 wd-xs-400 pd-25 pd-xs-40 bg-white rounded shadow-base">
        <div class="signin-logo tx-center tx-28 tx-bold tx-inverse"><span class="tx-normal">[</span> bracket <span class="tx-info">plus</span> <span class="tx-normal">]</span></div>
        <div class="tx-center mg-b-40">The Admin Template For Perfectionist</div>

        <form method='POST'>
          {% csrf_token %}
          {% crispy form %}

          <div class="form-group tx-12">By clicking the Sign Up button below, you agreed to our privacy policy and terms of use of our website.</div>
          <button type="submit" class="btn btn-info btn-block">Sign Up</button>
        </form>

      </div><!-- login-wrapper -->
    </div><!-- d-flex -->

    <script src="{% static "lib/jquery/jquery.min.js" %}"></script>
    <script src="{% static "lib/jquery-ui/ui/widgets/datepicker.js" %}"></script>
    <script src="{% static "lib/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "lib/select2/js/select2.min.js" %}"></script>
    <script>
      $(function(){
        'use strict';

        $('.select2').select2({
          minimumResultsForSearch: Infinity
        });
      });
    </script>

  </body>
</html>