games/urls.py
from django.urls import path

from .views import ListGamesView

app_name = 'games'
urlpatterns = [
    path('', ListGamesView.as_view(), name='list'),
]

shops/urls.py
from django.urls import path

from .views import CreateShop, UpdateShop, ListShopsView, ShopDelete, SwitchFavouriteShop

app_name = 'shops'
urlpatterns = [
    path('', ListShopsView.as_view(), name='list'),
    path('add/', CreateShop.as_view(), name='add'),
    path('<slug:slug>/edit', UpdateShop.as_view(), name='edit'),
    path('<slug:slug>/delete', ShopDelete.as_view(), name='delete'),
    path('<slug:slug>/like', SwitchFavouriteShop.as_view(), name='like'),
]

shops/models.py
from datetime import datetime
import itertools

from django.db import models
from django.conf import settings
from django.utils.text import slugify
# Create your models here.


class ShopModel(models.Model):

    name = models.CharField(max_length=64)
    slug = models.SlugField(max_length=64, unique=True)
    elastic_name = models.SlugField(max_length=64, unique=True, blank=True, null=True)
    #description = models.TextField(blank=True, default='') # tTODO: remove this field
    short_description = models.CharField(max_length=256, blank=True, default='')
    website = models.URLField(max_length=64)
    facebook = models.URLField(max_length=64, blank=True, null=True)
    verified_at = models.DateTimeField(null=True)
    verified_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='verified_shops')

    deleted_at = models.DateTimeField(null=True)
    deleted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, related_name='deleted_shops')

    def save(self, *args, **kwargs):

        if not self.slug:
            max_length = self._meta.get_field('slug').max_length
            slug_candidate = slug_original = slugify(self.name, allow_unicode=False)
            Klass = self.__class__
            for i in itertools.count(1):
                if not Klass.objects.filter(slug=slug_candidate).exists():
                    break
                suffix = f"-{i}"
                suffix_length = len(suffix)
                slug_base = slug_original[:max_length - suffix_length]
                slug_candidate = ''.join([slug_base, suffix])
            self.slug = slug_candidate
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):

        self.deleted_at = datetime.now()
        self.save()

    def __str__(self):
        return self.name

class UserPreferedShops(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='preferd_shops'
    )
    shop = models.ForeignKey(
        ShopModel,
        on_delete=models.CASCADE,
        related_name='dedicated_customers',
    )
    joined_at = models.DateTimeField(auto_now=True, null=False)
    unsubscribed_at = models.DateTimeField(null=True)

shops/forms.py
from django import forms

from .models import ShopModel

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field, Submit, Button, Div
from crispy_forms.bootstrap import FormActions

class ShopForm(forms.ModelForm):

    class Meta:
        model = ShopModel
        fields = ['name', 'short_description', 'website', 'facebook', 'elastic_name']

    def __init__(self, *args, **kwargs):
        super(ShopForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Field('name', placeholder='Enter shop name'),
            Field('short_description', placeholder='Enter short description (optional)'),
            Field('website', placeholder='Enter site url'),
            Field('facebook', placeholder='Enter facebook fanpage url (optional)'),
            Field('elastic_name', placeholder='Enter elasticsearch name'),
            FormActions(
                Submit('submit', 'Save'),
                Submit('verify', 'Save &amp; Verify'),
                #Submit('cancel', 'Cancel', css_class='btn btn-danger')
            )
        )

class SuggestShopForm(forms.ModelForm):

    class Meta:
        model = ShopModel
        fields = ['name', 'website']

    def __init__(self, *args, **kwargs):
        super(SuggestShopForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div(
                Div(
                    Field('name', placeholder='Enter shop name', css_class='form-control', template='layouts/baseinput.html'),
                    Field('website', placeholder='Enter site url', css_class='form-control mg-md-l-10 mg-t-10 mg-md-t-0', template='layouts/baseinput.html'),
                    Submit('submit', 'Recommend', css_class='btn btn-info pd-y-13 pd-x-20 bd-0 mg-md-l-10 mg-t-10 mg-md-t-0 tx-uppercase tx-11 tx-spacing-2'),
                    css_class='d-md-flex pd-y-20 pd-md-y-0'
                ),
                css_class='d-flex align-items-center justify-content-center ht-md-80 pd-x-20'
            )
        )

shops/views.py
from datetime import datetime, timedelta

from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.db.models import Count, Q
from django.urls import reverse, reverse_lazy
from django.http import HttpResponseRedirect

# Create your views here.

from elasticsearch import Elasticsearch
from elasticsearch_dsl import Search

from .forms import ShopForm, SuggestShopForm
from .models import ShopModel, UserPreferedShops


class ListShopsView(LoginRequiredMixin, ListView):

    model = ShopModel
    template_name = "shops/verified_list.html"
    context_object_name = "shops"

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .exclude(verified_by=None)
            .annotate(likes_count=Count("dedicated_customers"))
            .annotate(
                user_choice=Count(
                    "dedicated_customers",
                    filter=Q(dedicated_customers__user=self.request.user),
                )
            )
            .order_by("-likes_count", "name")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["suggestion_form"] = SuggestShopForm()

        # if self.request.user.has_perm('shops.can_verify'):
        if True:
            context["awaiting_confirmation"] = (
                super().get_queryset().filter(verified_by=None, deleted_at=None)
            )
        return context

    def post(self, request, *args, **kwargs):
        self.suggestion_form = SuggestShopForm(self.request.POST or None)
        if self.suggestion_form.is_valid():
            self.suggestion_form.save()

        return redirect(reverse("shops:list"))


class CreateShop(LoginRequiredMixin, CreateView):
    model = ShopModel
    template_name = "shops/form.html"
    form_class = ShopForm
    success_url = "/"


class UpdateShop(LoginRequiredMixin, UpdateView):
    model = ShopModel
    template_name = "shops/form.html"
    form_class = ShopForm
    success_url = "/"

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        if "verify" in self.request.POST:
            form.instance.verified_at = datetime.now()
            form.instance.verified_by = self.request.user

        return form


class SwitchFavouriteShop(LoginRequiredMixin, View):
    def get(self, request, slug):

        shop = ShopModel.objects.get(slug=slug)
        try:
            preference = UserPreferedShops.objects.get(user=request.user, shop=shop)
            preference.delete()
        except UserPreferedShops.DoesNotExist:
            UserPreferedShops(user=request.user, shop=shop).save()

        return redirect(reverse_lazy("shops:list"))


class ShopDelete(LoginRequiredMixin, DeleteView):
    model = ShopModel
    template_name = "shops/shop_confirm_delete.html"
    success_url = reverse_lazy("shops:list")

    def delete(self, request, *args, **kwargs):

        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        self.object.deleted_by = self.request.user
        success_url = self.get_success_url()
        self.object.delete()
        return HttpResponseRedirect(success_url)


class OffersList(LoginRequiredMixin, TemplateView):

    template_name = "shops/offers/list.html"

    def get_context_data(self, **kwargs):
        params = self.request.GET

        sort_orders = {
            "default": ("-discount_percentage",),
            "deal": ("-discount_percentage",),
            "discount": ("-discount_value",),
            "price": ("price", "-discount_percentage"),
        }

        context = super().get_context_data(**kwargs)

        client = Elasticsearch()

        search = (
            Search(using=client, index=f"test-products-{params.get('shop', '*')}")
            .filter("range", discount_percentage={"gt": "0.0", "lte": 100.0})
            .filter(
                "range", _meta__last_update={"gt": datetime.now() - timedelta(days=1)}
            )  # Filter only currently updated offers
            .sort(*sort_orders.get(params.get("sort", "default")))
            .exclude("match", out_of_stock=True)
        )

        q = params.get("q")
        if q:
            search = search.filter("match", name=q)

        # pagination
        pagesize = int(params.get("pagesize", 100))
        page = int(params.get("page", 1))
        search = search[(page - 1) * pagesize : page * pagesize]

        context["offers"] = search.execute()

        print(context["offers"])

        return context

shops/templates/shops/form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}
{% block content %}


  <div class="row mg-t-80">
    <div class="col-xl-6 offset-xl-3">
      <form method="POST">
      <div class="form-layout form-layout-4">
        {% if form.instance.pk %}
            <h6 class="br-section-label mg-t-0">{% trans 'Edit' %} {{form.instance.name}} </h6>
            <p class="br-section-text">{% trans 'Edit &amp; Verify existing shop instance' %} </p>
        {% else %}
            <h6 class="br-section-label mg-t-0">{% trans 'Create new shop' %}</h6>
            <p class="br-section-text">{% trans 'Create &amp; Verify new shop instance' %} </p>
        {% endif %}
        {% crispy form %}
      </div><!-- form-layout -->
      </form>
    </div><!-- col-6 -->
  </div>

{% endblock %}

shops/templates/shops/list.html
{% extends 'base.html' %}

shops/templates/shops/shop_confirm_delete.html
{% extends "base.html" %}

{% load i18n %}
{% block content %}
<form method="post">{% csrf_token %}
    <p>{% blocktrans with object=object %} "Are you sure you want to delete <b>{{ object }}</b>?"{% endblocktrans %}</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

shops/templates/shops/verified_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
  {% for shop in shops %} 
  {% if forloop.counter0|divisibleby:4 %}
  <div class="row">
  {% endif %}
    <div class="col-md-6 col-lg-3 mg-t-20 mg-md-t-0 pb-4">
      {% include 'shops/partials/shop_card.html' %}
    </div><!-- col -->
  {% if forloop.counter|divisibleby:4 or forloop.last %}</div>{% endif %}
  {% endfor %}

  
  {% if suggestion_form %}
  <div class="row mg-t-80">
    <div class="col-xl-6 offset-xl-3">
      <form method="POST" action="?next={% url 'shops:list' %}">
      <div class="form-layout form-layout-4">
        <h6 class="br-section-label mg-t-0">{% trans "Can't find your favourite shop?" %}</h6>
        <p class="br-section-text mg-b-20 mg-l-20">{% trans "Fill the form below and we'll add it to the list." %} </p>
        {% crispy suggestion_form %}
      </div><!-- form-layout -->
      </form>
    </div><!-- col-6 -->
  </div>
  {% endif %}


  <h6 class="tx-inverse tx-uppercase tx-bold tx-14 mg-t-80 mg-b-10"> {% trans "List of unverified shops" %} </h6>
  <p class="br-section-text">{% trans "Please verify them as soon as possible" %}</p>
  <div class="row">
    <div class="col-xl-6 mg-t-20 mg-lg-t-0 offset-xl-3 ">
      <div class="list-group list-group-striped">
        {% for unconfirmed in awaiting_confirmation %} 
        <div class="list-group-item pd-y-15 pd-x-20 d-xs-flex align-items-center justify-content-start">
          <img src="https://via.placeholder.com/500" class="wd-48 rounded-circle" alt="">
          <div class="mg-xs-l-15 mg-t-10 mg-xs-t-0 mg-r-auto">
              <a href="{{unconfirmed.website}}"><p class="mg-b-0 tx-inverse tx-medium">{{unconfirmed.name}}</p></a>
              <a href="{{unconfirmed.website}}"><span class="d-block tx-13">{{unconfirmed.website}}</span></a>
          </div>
          <div class="d-flex align-items-center mg-t-10 mg-xs-t-0">
            <a href="#" class="btn btn-outline-success btn-icon">
              <div class="tx-20"><i class="icon ion-md-checkmark-circle"></i></div>
            </a>
            <a href="{% url 'shops:delete' slug=unconfirmed.slug %}" class="btn btn-outline-danger btn-icon mg-l-5">
              <div class="tx-20"><i class="icon ion-md-remove-circle"></i></div>
            </a>
            <a href="{% url 'shops:edit' slug=unconfirmed.slug %}" class="btn btn-outline-primary btn-icon mg-l-5">
              <div class="tx-20"><i class="icon ion-md-create"></i></div>
            </a>
          </div>
        </div><!-- list-group-item -->
        {% endfor %}
      </div><!-- list-group -->
    </div><!-- col-6 -->
  </div>


{% endblock %}